print("      |\__/|  ")
print("      )    (  ")
print("     =\    /=")
print("       )  (   ")
print("_____ /    \ _____")
print("|     |    |     |")
print("|    /      \    |")
print("|    \      /    |")
print("|     \_  _/     |")
print("|_______((_______|  ")
print("         ))")
print("        ((")
